CONFIG_SRAM_SIZE=520

# Core SDL and Graphics Support
CONFIG_SDL_DISPLAY=y
CONFIG_INPUT_SDL_TOUCH=y

# Input Support
CONFIG_GPIO_EMUL=y
CONFIG_GPIO_EMUL_SDL=y

CONFIG_FLASH_SIMULATOR=y

CONFIG_THREAD_NAME=y
CONFIG_THREAD_RUNTIME_STATS=y

# Enable the full analyzer and command it to print itself
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_LOG=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5
